### ISSUE TITLE
Stop_all() problem when lot of audios is play

### ISSUE THREAD

**Issue by vdeville** [sbrl/soundbox#6]
I don't know why but if you have multiples sound in playing and you call stop method, All sounds is not properly pause. It's very strange behavior and totally random.

**Comment by sbrl** [comment]
Hrm. That was a tough one!

Turns out 2 things were wrong:

1. You forgot to add the braces to the `for` loop (or I removed them by accident, I can't remember)
2. We need to shallow-clone the instances array before iterating over it if we're going to fire the ended event artificially, as in the `ended` event instances remove themselves, changing the legngth of the array and preventing the iterator from iterating over the entire array and messing things up, as the browser is single-threaded (unless you use web workers, which don't have access to the DOM anyway).

Does the latest master there fix the issue for you too? If so I'll release v0.3.4 to fix it.

**Comment by vdeville** [comment]
Yes it's good for me, tested and approved on master ;)

**Comment by sbrl** [comment]
Awesome! I'll get releasing v0.3.4 then.

**Comment by sbrl** [comment]
Ah, thanks! I released it a little while ago, but must have forgotten to come back & update this issue.

Thanks again for your help in improving soundbox!

**Comment by vdeville** [comment]
No problem, if you are interested to see usage of your library you can find in my github ;)
https://github.com/MyTheValentinus/soundbox
Thanks !

**Comment by vdeville** [comment]
Hello,
I re-open this issue, the problem is not resolved. After lot of try the bug reppear.
When i play for example 10 songs, and call stopAll, all song are not pause.

Thanks

**Comment by sbrl** [comment]
I can't reproduce this currently with my example test. Could you perhaps provide some additional information please?

For example, what does `<soundbox_variable_name>.instances` contain when the bug occurs?

Is there a particular way that you have to do it in order for the bug to occur? Maybe it's a specific sequence of events that cause it to break?

**Comment by vdeville** [comment]
Do you have a email ? I send you link of my current usage and test page ?
Thanks

**Comment by sbrl** [comment]
Yep! It's `sbrl {at} starbeamrainbowlabs (dot) com`.

**Comment by vdeville** [comment]
Hom i'm so confused, after full refresh of my cache, is working like a charm. I re-close this issue. 
I'm sorry

**Comment by sbrl** [comment]
Ah, awesome! Glad it's working. It's no problem at all!

In the future, you may wish to keep the developer tools open in your browser, and tick the "disable cache" box on the _network_ tab when working on a project.

**Comment by vdeville** [comment]
Yes i know, but forget this time. Grrr

**Comment by sbrl** [comment]
Ah, we all do that! I've done it several times and spent 1/2 hour figuring out which cache is responsible for holding on to the old file - when in actuality I've got the wrong file open or forgot to clear my browser's cache..... lol :P

**Comment by vdeville** [comment]
#MyDevelopperLife
